---

- name: Apt Modules Playbook
  hosts: localhost
  tasks:
  - name: install redis on Debian based distros 
    apt:
      name: redis-server
      state: present
      update_cache: true
    become: true
    when: ansible_os_family == 'Debian'

  - name: ensure specific version of php7.2 is installed
    apt:
      name: php7.2=7.2.10-0ubuntu0.18.04.1
      state: present
      update_cache: true
    become: true
  
  - name: ensure php7.2 and php7.2-mysql are installed
    apt:
      name: 
        - php7.2
        - php7.2-mysql
      state: present
      update_cache: true
    become: true
  
  - name: install php7.2 from a .deb on the internet
    apt:
      deb: http://security.ubuntu.com/ubuntu/pool/main/p/php7.2/php7.2_7.2.10-0ubuntu0.18.04.1_all.deb
      state: present
    become: true
    register: apt_output
    when: ansible_os_family == 'Debian'

  - name: ensure nginx is not installed and autoremove unneeded deps
    apt:
      name: nginx
      state: absent
      autoremove: true
    become: true
  
  - name: ensure latest version of php7.2 is installed
    apt:
      name: php7.2
      state: latest
      update_cache: true
    become: true
  
  - name: ensure latest versions of php7.2 and php7.2-mysql are installed
    apt:
      name: 
        - php7.2
        - php7.2-mysql
      state: latest
      update_cache: true
    become: true
  
  - name: update all packages installed on the system
    apt:
      name: "*"
      state: latest
      force_apt_get: true
      update_cache: true
    become: true
  
  # to downgrade a package version , first remove the current downloaded version and download the older verion.
  - name: ensure php7.2 is not installed
    apt:
      name: php7.2
      state: absent
      autoremove: true
    become: true

  - name: ensure older version of php7.2 is installed
    apt:
      name: php7.2=7.2.3-1ubuntu1
      state: present
      update_cache: true
    become: true